version: 0.2
phases:
  pre_build:
    commands:
      - echo Log com Amazon ECR..
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 677253534368.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=677253534368.dkr.ecr.us-east-1.amazonaws.com/eureka-server
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build comecando na data `date`
      - echo building jar file
      - mvn clean install
      - echo building dockerfile
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build finalizado com sucesso em `date`
      - echo Fazendo push da imagem para o ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Gerando artefato da imagem para o ECS
      - printf '[{"name":"eureka-server","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - target/eureka-server-0.0.1-SNAPSHOT.jar